#!/bin/bash
directory=$PWD;
cat ~/.bash_profile | sed -e "s|.*PT_BASH_TOOLS_ROOT.*|export PT_BASH_TOOLS_ROOT=$directory|g" > /tmp/bash_profile.txt
cat /tmp/bash_profile.txt
mv /tmp/bash_profile.txt ~/.bash_profile

source ~/.bash_profile
