#!/bin/bash

since=`date +%Y-%m-01`
until=`date +%Y-%m-%d`


usage() {
  echo "usage: tcm [-s YYYY-MM-DD] [-u YYYY-MM-DD]"
  exit
}

while getopts "u:s:"  opt
do
  case $opt in
    s)
      since=$OPTARG
      ;;
    u)
      until=$OPTARG
      ;;
    \?)
      echo "invalid option"
      usage
      ;;
  esac
done

echo "date range from $since to $until"

files=$(git grep -n -e '^\s*TEST' AtmosRmu/* | cut -d : -f 1,2 | awk -F':' '{printf "-L%s,%s %s\n", $2,$2,$1}')

printf "%-20s %-10s %-10s %-10s \n" "COMMITTER" "ADDED" "DELETED" "COMMITS"

while read -r line; do
  blame=$(git blame -p $line | grep 'author ')
  usernames+="${blame//author /} "
done <<< "$files"

sorted = ($for l in ${usernames[@]}; do echo $)
echo "$usernames"

#sort file | uniq -c | awk '{printf "%s : %s\n", $1, $2}'
